### ISSUE TITLE
Bad CSS on Roles editor page

### ISSUE THREAD

**Issue by asinck** [allejo/bzion#105]
This can be seen when editing a role, such as [here](http://sandbox.leaguesunited.org/admin/role/5). The permissions list spills over the alloted space.

A grid for these might be a good part of the solution.

![image](https://user-images.githubusercontent.com/11052719/30517958-6e4ba4f8-9b24-11e7-823e-f9fd1971b5ec.png)

**Comment by asinck** [comment]
Notably, these even spilled over into the footer.

**Comment by asinck** [comment]
These also ignore mobile-responsiveness.

**Comment by allejo** [comment]
linking #72
