### ISSUE TITLE
Pizza Map description is missing a word

### ISSUE THREAD

**Issue by asinck** [allejo/bzion#121]
[link](http://sandbox.leaguesunited.org/maps/10)

**Edit:** The link is now invalid.

**Comment by allejo** [comment]
Could you elaborate on this? Is it something you can edit manually or is in the template of the map card?

**Comment by asinck** [comment]
Whoops, I deleted the Pizza map while testing ... the link is now invalid. I can't find the original text. I also forgot that I would have been able to edit it. If that was a real map (instead of just a test map), you can paste me the map's description and I'll be able to fix it.

**Comment by allejo** [comment]
So this was just an issue with the content, not the site itself, right?

**Comment by asinck** [comment]
Oh, true.
