### ISSUE TITLE
League Maps page - No explanatory hover text on icons (jumping, rico, ...)

### ISSUE THREAD

**Issue by asinck** [allejo/bzion#124]

**Comment by allejo** [comment]
#104 mentions that there's no hover text for the ricochet icon. Is there somewhere else where there's hover text?

**Comment by asinck** [comment]
http://sandbox.leaguesunited.org/maps/

**Comment by allejo** [comment]
Can you confirm this one? I can't reproduce. On that page, if I hover over the icons long enough there's hover text that appears for me. Granted it's not a JS solution and it's just a `title` attribute.

**Comment by asinck** [comment]
**Now** it works...
