### ISSUE TITLE
Map creation page - Possible to create a map with a duplicate alias

### ISSUE THREAD

**Issue by asinck** [allejo/bzion#125]
In this case, the aliased URL will go to the original map that had that alias.

**Comment by allejo** [comment]
Can't reproduce, could you elaborate on this issue?

![image](https://user-images.githubusercontent.com/1246453/30519315-184a33a2-9b48-11e7-991d-01ba6ac24c06.png)

**Comment by asinck** [comment]
This may be related to #122 . I think I may be crossing up "alias" and the URL page.

For the Pizza map, I edited it to have an alias of '2', but going to http://sandbox.leaguesunited.org/maps/2 yields the HiX page.

**Comment by allejo** [comment]
I think I'll disallow aliases with just numbers since that can be confused for IDs which is what's going here. Since the hix map has an ID of 2, it's treating it as an ID and not an alias
