### ISSUE TITLE
Deleted teams retain text referencing team avatar

### ISSUE THREAD

**Issue by Zehra** [allejo/bzion#129]
It seems teams retain a text based reference to their team avatar even though their team is deleted/non-existent.

Example: Sample team Sample team's avatar

**Comment by allejo** [comment]
**To do**

- [ ] Add migration to reset avatars for all disabled/deleted teams
- [ ] Make sure to reset avatar on team delete
- [ ] Reset the avatar for a team when `::getAvatar()` is called on a disabled/deleted model
