### ISSUE TITLE
Buttons fail to display on resize

### ISSUE THREAD

**Issue by Zehra** [allejo/bzion#131]
It seems buttons fail to display when the web browser is resized.

Default display of content.
![1 sample news default display size](https://user-images.githubusercontent.com/22282963/30526408-fbca31dc-9be7-11e7-8dd6-5c4e2dc092fe.png)

Non-default display of content.
![1 sample news non-default display size](https://user-images.githubusercontent.com/22282963/30526411-0b53c992-9be8-11e7-9fcb-3ecac20102e7.png)

The buttons for delete and edit appear in the first screenshot with default display.
They disappear in the next when the browser resizes.
(The edit and delete buttons.)

Note: The screenshots were taken with Firefox on Windows 10.

**Comment by allejo** [comment]
These buttons are moved to the mobile menu at a lower screen size, however the fact that the mobile menu icon is gone is what's concerning. I'll investigate

**Comment by allejo** [comment]
Closed in a56d4bbcc0a29e070e6b3e6592a0a5573d7f0780
