### ISSUE TITLE
Players reported as playing on both teams

### ISSUE THREAD

**Issue by Zehra** [allejo/bzion#133]
It seems it's possible to report a player as having played on both generic teams.
Example: Sample player (green team) - Sample player (red team.)

This seems to affect fun matches and special event matches.

**Comment by allejo** [comment]
Official matches are not affected?

**Comment by Zehra** [comment]
There does not seem to be a way of entering an official match in which a player would appear in both teams.

**Comment by Zehra** [comment]
Correction to my previous statement.
It seems possible to enter semi-official matches where an official and generic team in which a player is on both teams.
