### ISSUE TITLE
Map list improvements

### ISSUE THREAD

**Issue by Zehra** [allejo/bzion#156]
1. **Additional details on maps, such as randomly generated, worldsize, and game mode.**
(Some discussions suggest that AHOD along with other modes might be added in the future.)

2. **Change wording to be positive.**
_"Jumping is disabled on this map"
"Ricochet is disabled on this map"_
**Positive version of the above.**
_"Jumping has not been enabled in this map"
"Richochet has not been enabled in this map"_

**Comment by allejo** [comment]
> **Change wording to be positive.**
> "Jumping is disabled on this map"
> "Ricochet is disabled on this map"
> **Positive version of the above.**
> "Jumping has not been enabled in this map"
> "Richochet has not been enabled in this map"

If we're getting into wording, "has not been enabled" implies that it will be enabled in the future even though it's not true.

**Comment by Zehra** [comment]
Maybe **"Is not enabled"** is a better choice?
Technically "Jumping" and "Ricochet" options are "enabled" since they aren't disabled in BZFS.
(As far as I'm aware.)

**Comment by allejo** [comment]
I can see about adding additional info to maps once things like AHOD is introduced into the mix. However, I'm hesitant about changing the wording for now. I may change my mind later on.

**Comment by allejo** [comment]
Map model needs the following changes:

- [ ] (int) World size
- [ ] (bool) Randomly generated
- [ ] (enum) Game mode

**Comment by allejo** [comment]
@Zehra I did revisit the wording of these messages and changed them to sound more natural, e.g.

- "Jumping is (allowed|not allowed) on this map"
- "This map (has|does not have) ricochet shots"
