### ISSUE TITLE
Page Designs Testing

### ISSUE THREAD

**Issue by allejo** [allejo/bzion#22]
As I'm designing the pages to be mobile responsive and to look good, I'll be posting what pages are finished (meaning they're fully mobile responsive). Now, I need everyone's help to test these pages on their different browsers and mobile devices to make sure they work as they should.

If you see some weird issues, please post a screenshot of the issue and what device/browser you are using.

**Browser Requirements**

- Chrome
- Firefox
- IE10+
- Safari

**Pages Ready for Testing**

- [ ] [Landing Page](http://bzion.bzpro.net/dev.php)
- [ ] [News Page](http://bzion.bzpro.net/dev.php/news)
    - [ ] [News Article](http://bzion.bzpro.net/dev.php/news/1)
    - [ ] [News Article (Delete)](http://bzion.bzpro.net/dev.php/news/1/delete) *
    - [ ] [News Article (Edit)](http://bzion.bzpro.net/dev.php/news/1/edit) *
    - [ ] [News Article (New)](http://bzion.bzpro.net/dev.php/news/new) *
- [ ] [Teams Page](http://bzion.bzpro.net/dev.php/teams)
    - [ ] [Team Page (Individual)](http://bzion.bzpro.net/dev.php/teams/good-separation)
    - [ ] [Team Page (Create)](http://bzion.bzpro.net/dev.php/teams/new)
    - [ ] [Team Page (Edit)](http://bzion.bzpro.net/dev.php/teams/good-separation/edit) *
    - [ ] [Team Page (Delete)](http://bzion.bzpro.net/dev.php/teams/good-separation/delete) *
- [ ] [Player List](http://bzion.bzpro.net/dev.php/players)
    - [ ] [Player Profile](http://bzion.bzpro.net/dev.php/players/alezakos) **
    - [ ] [Player Settings](http://bzion.bzpro.net/dev.php/profile/edit)
- [ ] [Admin List](http://bzion.bzpro.net/dev.php/admins)
- [ ] [Custom page](http://bzion.bzpro.net/dev.php/rules)
    - [ ] [Custom page (Edit)](http://bzion.bzpro.net/dev.php/rules/edit)*

\* - Requires admin perms to view
\** - Requires admin perms view to extra sections

I'll be adding pages here as I finish them, so be sure to check back. I'll also be checking off the pages as they've been tested by several people.

Thanks for the help, everyone!

**Last Update**: March 20, 2015

**Comment by allejo** [comment]
Commits 4b033bb6abec66f8265ba0c900f4fcb01f1bc528 and 2c470112a14e2737448868b8ff7b72bee2513c6b fix issues on iOS devices. The stylesheet was lacking the proper vendor prefixers that Autoprefixer was failing to add. We'll be relying on Bourbon for this from now on and Autoprefixer has been removed as of ec8ab2560330ead0566379464450d5c71c46adbc.

**Comment by kongr45gpen** [comment]
![Individual Team Page (Android Chrome)](https://cloud.githubusercontent.com/assets/720678/6730599/df49ee1a-ce46-11e4-8cf7-197644a7f852.png)

![Individual Team Page (Firefox)](https://cloud.githubusercontent.com/assets/720678/6730643/36b46ee6-ce47-11e4-854a-c8e0fb068741.png)

**Comment by allejo** [comment]
@kongr45gpen Buttons on mobile have been fixed in 1c317b8b5ae9afe512b4cc0f0f36c185ec03eea1. They'll appear in the mobile menu instead of buttons next to the page title

**Comment by allejo** [comment]
![Flexbox fail](http://i.imgur.com/Ipgeqei.jpg)

The date should be on its own line and the opponent and score should be on a different line together

**Comment by kongr45gpen** [comment]
![Player profile admin notes buttons](https://cloud.githubusercontent.com/assets/720678/6846877/6f00147a-d3ca-11e4-8d3b-d0fb8e7388bd.png)

**Comment by kongr45gpen** [comment]
![Big buttons on small screens](https://cloud.githubusercontent.com/assets/720678/7555659/42780cd2-f75b-11e4-9402-f5762ed820c9.png)
