### ISSUE TITLE
[Enhancement] - weekly tournaments

### ISSUE THREAD

**Issue by Snake12534** [allejo/bzion#31]
Weekly GU/Duc Tournaments for Team Standings using advertisements revenue to pay for bzflag prizes.

**Comment by Ashvala** [comment]
This is a CMS. Talk to the league admins about bringing weekly tournaments to the league. However, there are team-stats and info available via an API, so, if you feel so inclined to build the weekly tournament as a third party service, feel free to do so. As it stands, we don't see the necessity of it as being a part of the bzion core.
