### ISSUE TITLE
Show individual player ELO

### ISSUE THREAD

**Issue by kongr45gpen** [allejo/bzion#52]
- [x] Show each player's win ratio
- [ ] Show each player's ELO score
- [ ] Add a history graph

**Comment by allejo** [comment]
Where is this data going to be coming from?

**Comment by kongr45gpen** [comment]
Right now, the only source of data we have for player stats is how many matches they won with their teams, and how many caps their team did.

I don't know if the score is going to be exactly an ELO score though, since calculating ELOs is hard, so we might have to go with something simpler, such as a win/loss ratio.

**Comment by allejo** [comment]
That sounds reasonable with the data we're have access too right now. Probably with the next major release of League Overseer, we'll be able to get this more accurate with a lot more data being reported.

**Comment by allejo** [comment]
Superseded by #71
