### ISSUE TITLE
Add more attributes for maps

### ISSUE THREAD

**Issue by kongr45gpen** [allejo/bzion#62]
More information can be added for league maps, such as:
- [ ] Map size
- [ ] Whether jumping is enabled or not
- [ ] Shot number

**Comment by allejo** [comment]
I'd like to bring up the possibility of maybe having something like [this (a radar view of the entire map)](http://static.bzexcess.com/downloads/bzWorlds/) for maps as well?

**Comment by allejo** [comment]
893aa34f645d0836d59f10d9d38520f63aa2d4e2 #90 and #156
