### ISSUE TITLE
New ELOs for players + teams

### ISSUE THREAD

**Issue by allejo** [allejo/bzion#71]
[LU council has officially voted in favor of the idea](https://forums.bzflag.org/viewtopic.php?f=114&p=173426&sid=ca03167e5e3a991fb86599b5a9481edd#p173426). So, let's get planning!

### Notes

- LeagueOverseer 1.1.x already reports player BZIDs and we've been using them for Matches so that should be all the information we need going forward.
- All players would start with a base ELO of 1200 same as teams upon creation; ~~we won't retroactively calculate ELOs for players~~
- The ELO will be displayed on player profiles on the site but **not** in player mottos, ~~so the API controller shouldn't need any changes~~

### To do

*Moved to #81*

**Comment by shiyaoay** [comment]
This isn't a very serious comment, but I thought it's important to note that the new system doesn't just add new forms of ELO, but also allow any individual to start /official with other individuals for an official match. (I know we already know this, but for people who are clicking on the link to check this progress, they may not get the whole idea from the title :P)

**Comment by allejo** [comment]
All further discussion for this should be moved to the respective PR: #81
