### ISSUE TITLE
Kicking players from a team results in "Generic Error"

### ISSUE THREAD

**Issue by asinck** [allejo/bzion#97]
When kicking a player from their team, a "generic error" screen is displayed. The kick does however process correctly.

**Comment by allejo** [comment]
Tagging as invalid; this should be a issue with me not creating the database structure correctly. I'll close once I can confirm

**Comment by allejo** [comment]
Poor database structure on my part was the cause of this error. Foreign keys need to fixed/looked into but that's for another issue/project.
